# Setup
title:               Willy Kim
tagline:             ''
description:         ''
url:                 https://willy.kim
baseurl:             ''
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Willy Kim
  url:               https://willy.kim
  email:             wkim149@gmail.com

# Gems
plugins:
  - jekyll-paginate
